// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkW24iKhjHdDf_fvWNVo9sXZMxqgDxq1E',
    appId: '1:637975748558:web:974c5eac9736c913bfd59f',
    messagingSenderId: '637975748558',
    projectId: 'bazzar-book-project',
    authDomain: 'bazzar-book-project.firebaseapp.com',
    storageBucket: 'bazzar-book-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbQhpoIyvXERJue8NCjd9m12h90ouP9TA',
    appId: '1:637975748558:android:92b8de542097eb28bfd59f',
    messagingSenderId: '637975748558',
    projectId: 'bazzar-book-project',
    storageBucket: 'bazzar-book-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZKRq1oTyKFBIZFcT3E0a_gdQLJ1SESQ',
    appId: '1:637975748558:ios:07d21014e0c88fb8bfd59f',
    messagingSenderId: '637975748558',
    projectId: 'bazzar-book-project',
    storageBucket: 'bazzar-book-project.firebasestorage.app',
    iosBundleId: 'com.example.bazzarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZKRq1oTyKFBIZFcT3E0a_gdQLJ1SESQ',
    appId: '1:637975748558:ios:07d21014e0c88fb8bfd59f',
    messagingSenderId: '637975748558',
    projectId: 'bazzar-book-project',
    storageBucket: 'bazzar-book-project.firebasestorage.app',
    iosBundleId: 'com.example.bazzarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkW24iKhjHdDf_fvWNVo9sXZMxqgDxq1E',
    appId: '1:637975748558:web:b6c60e6a10830aebbfd59f',
    messagingSenderId: '637975748558',
    projectId: 'bazzar-book-project',
    authDomain: 'bazzar-book-project.firebaseapp.com',
    storageBucket: 'bazzar-book-project.firebasestorage.app',
  );
}
